# -*- coding: utf-8 -*-
"""Air_GUI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xg5mFIwO9182lvli8xVQcZNrOsQ0JLcM
"""

!pip install -q gradio joblib

import pandas as pd
import joblib
import gradio as gr

model = joblib.load("air_quality_model.pkl")
features = joblib.load("air_quality_features.pkl")

def predict_co(
    pt08_s1_co,
    nmhc_gt,
    c6h6_gt,
    pt08_s2_nmhc,
    nox_gt,
    pt08_s3_nox,
    no2_gt,
    pt08_s4_no2,
    pt08_s5_o3,
    temperature,
    humidity,
    absolute_humidity,
    date,
    hour
):

   date = pd.to_datetime(date)
   year = date.year
   month = date.month
   day = date.day
   day_of_week = date.dayofweek
   is_weekend = int(day_of_week >= 5)
   is_rush_hour = int(hour in [7, 8, 9, 17, 18, 19])



   input_data = pd.DataFrame([{
        "PT08.S1(CO)": pt08_s1_co,
        "NMHC(GT)": nmhc_gt,
        "C6H6(GT)": c6h6_gt,
        "PT08.S2(NMHC)": pt08_s2_nmhc,
        "NOx(GT)": nox_gt,
        "PT08.S3(NOx)": pt08_s3_nox,
        "NO2(GT)": no2_gt,
        "PT08.S4(NO2)": pt08_s4_no2,
        "PT08.S5(O3)": pt08_s5_o3,
        "T": temperature,
        "RH": humidity,
        "AH": absolute_humidity,
        "year": year,
        "month": month,
        "day": day,
        "hour": hour,
        "day_of_week": day_of_week,
        "is_weekend": is_weekend,
        "is_rush_hour": is_rush_hour
    }])


   input_data = input_data[features]
   prediction = model.predict(input_data)[0]

   return f"Predicted CO Concentration: {prediction:.2f}"

with gr.Blocks(title="Air Quality Prediction") as demo:

    gr.Markdown(
        """
         Air Quality Prediction System
        Enter the air-quality and environmental measurements below
        to predict **CO (Carbon Monoxide) concentration**.
        """
    )

    with gr.Row():

        with gr.Column():
            gr.Markdown("Air Quality Measurements")

            pt08_s1_co = gr.Number(
                label="PT08.S1(CO)",
                value=1000
            )

            nmhc_gt = gr.Number(
                label="NMHC(GT)",
                value=100
            )

            c6h6_gt = gr.Number(
                label="C6H6(GT)",
                value=10
            )

            pt08_s2_nmhc = gr.Number(
                label="PT08.S2(NMHC)",
                value=1000
            )

            nox_gt = gr.Number(
                label="NOx(GT)",
                value=100
            )

            pt08_s3_nox = gr.Number(
                label="PT08.S3(NOx)",
                value=1000
            )

            no2_gt = gr.Number(
                label="NO2(GT)",
                value=100
            )

            pt08_s4_no2 = gr.Number(
                label="PT08.S4(NO2)",
                value=1000
            )

            pt08_s5_o3 = gr.Number(
                label="PT08.S5(O3)",
                value=1000
            )

        with gr.Column():
            gr.Markdown("Environmental Measurements")

            temperature = gr.Number(
                label="Temperature (T)",
                value=15
            )

            humidity = gr.Number(
                label="Relative Humidity (RH)",
                value=50
            )

            absolute_humidity = gr.Number(
                label="Absolute Humidity (AH)",
                value=1
            )

            gr.Markdown("Date and Time")

            date = gr.Textbox(
                label="Date (YYYY-MM-DD)",
                value="2004-03-10"
            )

            hour = gr.Slider(
                minimum=0,
                maximum=23,
                step=1,
                value=12,
                label="Hour"
            )

    predict_button = gr.Button(
        "Predict CO Concentration"
    )

    output = gr.Textbox(
        label="Prediction Result"
    )

    predict_button.click(
        fn=predict_co,
        inputs=[
            pt08_s1_co,
            nmhc_gt,
            c6h6_gt,
            pt08_s2_nmhc,
            nox_gt,
            pt08_s3_nox,
            no2_gt,
            pt08_s4_no2,
            pt08_s5_o3,
            temperature,
            humidity,
            absolute_humidity,
            date,
            hour
        ],
        outputs=output
    )

demo.launch(share=True)